spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_ENV}/${DATABASE_NAME:systems_design_workshop}
    username: ${DB_USER_SECRET}
    password: ${DB_PWD_SECRET}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  output:
    ansi:
      enabled: ALWAYS
security:
  credentials:
    private-key: ${PK_SECRET}
    public-key: ${PUBLIC_KEY}

server:
  port: 9397

frontend:
  enable:
    host: ${FRONTEND_HOST:http://localhost:3000}
